### PR TITLE
Fix all dictionnaries about MySQL and MariaDB versions for built-in functions

### PR DESCRIPTION
**Pull request by niconoe-**
After long hours and hours of reviewing, I can share to you an up-to-date version of the dictionnaries for all MariaDB and MySQL versions currently supported on SQL-Parser 5.9.

Here are my sources:

<details>
  <summary>MySQL</summary>
  
MySQL 5.0: https://downloads.mysql.com/docs/refman-5.0-en.pdf Chapter 12.1
MySQL 5.1: https://downloads.mysql.com/docs/refman-5.1-en.pdf Chapter 12.1
MySQL 5.5: https://downloads.mysql.com/docs/refman-5.5-en.pdf Chapter 12.1
MySQL 5.6: https://web.archive.org/web/20221203223707/https://dev.mysql.com/doc/refman/5.6/en/built-in-function-reference.html
MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/built-in-function-reference.html
MySQL 8.0: https://dev.mysql.com/doc/refman/8.0/en/built-in-function-reference.html
MySQL 8.1: https://web.archive.org/web/20231001231110/https://dev.mysql.com/doc/refman/8.1/en/built-in-function-reference.html
MySQL 8.2: https://web.archive.org/web/20231204125724/https://dev.mysql.com/doc/refman/8.2/en/built-in-function-reference.html
MySQL 8.3: https://web.archive.org/web/20240522075210/https://dev.mysql.com/doc/refman/8.3/en/built-in-function-reference.html
MySQL 8.4: https://dev.mysql.com/doc/refman/8.4/en/built-in-function-reference.html
  
</details>

<details>
  <summary>MariaDB</summary>

> :warning: 
> About MariaDB, for versions that described differences with MySQL version I took all functions from the MySQL version source and used the "changelog-differences" to adapt the differences.
> Once done, as there is no fixed list for each version, I did manual comparison using information on:
> 1) MariaDB website, if available
> 2) Archives of MariaDB website using the wayback machine, if available
> 3) GitHub lookup in sources, minor version by minor version scooting for tags only otherwise.

MariaDB 10.0: https://mariadb.com/kb/en/function-and-operator-reference/
MariaDB 10.1: https://mariadb.com/kb/en/function-and-operator-reference/
MariaDB 10.2: https://mariadb.com/kb/en/function-differences-between-mariadb-102-and-mysql-56/
MariaDB 10.3: https://mariadb.com/kb/en/function-differences-between-mariadb-103-and-mysql-57/
MariaDB 10.4: https://mariadb.com/kb/en/function-differences-between-mariadb-10-4-and-mysql-8-0/
MariaDB 10.5: https://mariadb.com/kb/en/function-differences-between-mariadb-10-5-and-mysql-8-0/
MariaDB 10.6: https://mariadb.com/kb/en/function-differences-between-mariadb-10-6-and-mysql-8-0/
MariaDB 10.7: https://mariadb.com/kb/en/function-differences-between-mariadb-10-7-and-mysql-8-0/
MariaDB 10.8: https://mariadb.com/kb/en/function-differences-between-mariadb-10-8-and-mysql-8-0/
MariaDB 10.9: https://mariadb.com/kb/en/function-differences-between-mariadb-10-9-and-mysql-8-0/
MariaDB 10.10: https://mariadb.com/kb/en/function-differences-between-mariadb-10-10-and-mysql-8-0/
MariaDB 10.11: https://mariadb.com/kb/en/function-differences-between-mariadb-10-11-and-mysql-8-0/
MariaDB 11.0: https://mariadb.com/kb/en/function-differences-between-mariadb-11-0-and-mysql-8-0/
MariaDB 11.1: https://mariadb.com/kb/en/function-differences-between-mariadb-11-1-and-mysql-8-0/
MariaDB 11.2: https://mariadb.com/kb/en/function-differences-between-mariadb-11-2-and-mysql-8-0/
MariaDB 11.3: https://mariadb.com/kb/en/function-differences-between-mariadb-11-3-and-mysql-8-0/
MariaDB 11.4: https://mariadb.com/kb/en/function-differences-between-mariadb-11-4-and-mysql-8-0/

> Annexes for specific MariaDB functions' origin:

`BINLOG_GTID_POS`: Since MariaDB 10.0.2 : https://web.archive.org/web/20150912134347/https://mariadb.com/kb/en/mariadb/binlog_gtid_pos/
`(ST_)BOUNDARY`: Since MariaDB 10.1.2 : https://web.archive.org/web/20150410200336/https://mariadb.com/kb/en/mariadb/st_boundary/
`(ST_)BUFFER`: Since MariaDB 10.0.x : GitHub sources
`COLUMN_*`: Since MariaDB 5.3 : https://web.archive.org/web/20150925234848/https://mariadb.com/kb/en/mariadb/column_add/
`(ST_)ConvexHull`: Since MariaDB 10.1.2 : https://web.archive.org/web/20150410205523/https://mariadb.com/kb/en/mariadb/st_convexhull/
`CUME_DIST`: Since MariaDB 10.2.0 : https://web.archive.org/web/20200808042303/https://mariadb.com/kb/en/cume_dist/
`CURRENT_ROLE`: Since MariaDB 10.0.x : GitHub sources
`DECODE_HISTOGRAM`: Since MariaDB 10.0.x : GitHub sources
`DENSE_RANK`: Since MariaDB 10.2 : https://web.archive.org/web/20200302220448/https://mariadb.com/kb/en/dense_rank/
`FROM_BASE64`: Since MariaDB 10.0.5 : https://web.archive.org/web/20201028152820/https://mariadb.com/kb/en/from_base64/
`INET6_ATON`: Since MariaDB 10.0.12 : https://web.archive.org/web/20200924180425/https://mariadb.com/kb/en/inet6_aton/
`INET6_NTOA`: Since MariaDB 10.0.12 : https://web.archive.org/web/20200924190209/https://mariadb.com/kb/en/inet6_ntoa/
`IS_IPV4`: Since MariaDB 10.0.12: https://web.archive.org/web/20201026185357/https://mariadb.com/kb/en/is_ipv4/
`IS_IPV4_COMPAT`: Since MariaDB 10.0.12: https://web.archive.org/web/20200924190655/https://mariadb.com/kb/en/is_ipv4_compat/
`IS_IPV4_MAPPED`: Since MariaDB 10.0.12: https://web.archive.org/web/20200924183127/https://mariadb.com/kb/en/is_ipv4_mapped/
`IS_IPV6`: Since MariaDB 10.0.12: https://web.archive.org/web/20200924175447/https://mariadb.com/kb/en/is_ipv6/
`(ST_)IsRing` : Since MariaDB 10.1.2 : https://web.archive.org/web/20150410122112/https://mariadb.com/kb/en/mariadb/st_isring/
`LAST_DAY`: Since MariaDB 10.0.0 : GitHub sources
`LAST_VALUE`: Since MariaDB 10.0.0 : GitHub sources
`LASTVAL`: Since MariaDB 10.3: https://web.archive.org/web/20200919120627/https://mariadb.com/kb/en/previous-value-for-sequence_name/
`MASTER_GTID_WAIT`: Since MariaDB 10.0.9: https://web.archive.org/web/20140313211749/https://mariadb.com/kb/en/master_gtid_wait/
`MEDIAN`: Since MariaDB 10.3.3: https://web.archive.org/web/20200919124023/https://mariadb.com/kb/en/median/
`NATURAL_SORT_KEY`: Since MariaDB 10.7.0: https://mariadb.com/kb/en/natural_sort_key/
`NEXTVAL`: Since MariaDB 10.3: https://web.archive.org/web/20201028143308/https://mariadb.com/kb/en/next-value-for-sequence_name/
`(ST_)PointOnSurface`: Since MariaDB 10.1.2: https://web.archive.org/web/20150410150220/https://mariadb.com/kb/en/mariadb/st_pointonsurface/
`REGEXP_INSTR`: Since MariaDB 10.0.5: https://web.archive.org/web/20150925001520/https://mariadb.com/kb/en/mariadb/regexp_instr/
`REGEXP_REPLACE`: Since MariaDB 10.0.5: https://web.archive.org/web/20170113004307/https://mariadb.com/kb/en/mariadb/regexp_replace/
`REGEXP_SUBSTR`: Since MariaDB 10.0.5: https://web.archive.org/web/20171123231315/https://mariadb.com/kb/en/library/regexp_substr/
`SETVAL`: Since MariaDB 10.3: https://web.archive.org/web/20201020032819/https://mariadb.com/kb/en/setval/
`SYS_GUID`: Since MariaDB 10.6.1: https://mariadb.com/kb/en/sys_guid/
`TO_BASE64`: Since MariaDB 10.0.5 : https://web.archive.org/web/20201022130615/https://mariadb.com/kb/en/to_base64/
`TO_CHAR`: Since MariaDB 10.6.1 : https://mariadb.com/kb/en/to_char/
`WEIGHT_STRING`: Since MariaDB 10.0.5 : https://web.archive.org/web/20200804235441/https://mariadb.com/kb/en/weight_string/
  
</details>

> [!TIP]
> MySQL 8.4 has been also added to the list. :partying_face: 

Thanks a lot :slightly_smiling_face:

### CODE REVIEW

**Comment by niconoe-** [comment]
Here we go :smile: 

Just to enlight the 3 last commits : 
* Even if not being used as a function, the keyword "BINARY" is parsed by SQL-Parser as a function today, so I re-added it on every context to avoid BC Break.
* Prior to MySQL 5.7, "PROCEDURE ANALYSE" was a function, but SQL-Parser already considered it as the function "ANALYSE" called in a "PROCEDURE" context. Therefore, there was no need to consider it as a function on its own, and I removed it from the impacted contexts.
* There was a unit test where the keyword "RANK" was considered as an unknown token (Token 0, Flag 0) because of a missing definition in the dictionaries. As this is fixed, I also regenerated the expected tokens values for this test to consider "RANK" as expected.

All changes on the contexts are now free of BC Breaks and all tests are passing :+1: 

Ready for review @williamdes / @MauricioFauth :wink:

**Review by williamdes — APPROVED** [review]
I really like how this is easy to read 👏🏻

**Review by MauricioFauth — APPROVED** [review]
Thank you!

**Comment by niconoe-** [comment]
I just discovered few minutes ago that MySQL 9.0 has been released :sob: 

Don't consider MySQL 9.0 yet, I'll probably add the dictionnary in an incoming PR.

**Comment by liviuconcioiu** [comment]
> I just discovered few minutes ago that MySQL 9.0 has been released 😭
> 
> Don't consider MySQL 9.0 yet, I'll probably add the dictionnary in an incoming PR.

Even MariaDB 11.5 :)

**Pull request merged**
