### PR TITLE
Fix #413 - Adding guard checks before checking keyword

### LINKED ISSUE #413: Notice in ./vendor/phpmyadmin/sql-parser/src/Parser.php#483
Steps to reproduce:

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/sql&db=sakila](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/sql&db=sakila)
2. Paste `ANALYZE` - only with this word it can be reproduced.
3. Click on a database from the left side

Depending on settings, is either a warning or a notice. It happens on both QA_5_2 and master.

https://user-images.githubusercontent.com/25424343/213540973-04415631-9da4-43e6-b21d-072507dd723d.mp4

```
Notice in ./vendor/phpmyadmin/sql-parser/src/Parser.php#483
Trying to get property 'keyword' of non-object

Backtrace

Parser.php#377: PhpMyAdmin\SqlParser\Parser->parse()
Linter.php#126: PhpMyAdmin\SqlParser\Parser->__construct()
LintController.php#59: PhpMyAdmin\Linter::lint(string 'ANALYZE')
Routing.php#191: PhpMyAdmin\Controllers\LintController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/lint',
,
,
)
```

```
Warning in ./vendor/phpmyadmin/sql-parser/src/Parser.php#483
Attempt to read property "keyword" on null

Backtrace

    Parser.php#377: PhpMyAdmin\SqlParser\Parser->parse()
    Linter.php#125: PhpMyAdmin\SqlParser\Parser->__construct()
    LintController.php#59: PhpMyAdmin\Linter::lint(string 'ANALYZE')
    Routing.php#167: PhpMyAdmin\Controllers\LintController->__invoke(
    ,
    array,
    )
    Common.php#325: PhpMyAdmin\Routing::callControllerForRoute(
    ,
    ,
    ,
    )
    index.php#32: PhpMyAdmin\Common::run()
```

### PR DESCRIPTION
**Pull request by iifawzi**
Hi, this's fixing #413

fixes #413 

Signed-off-by: Fawzi Abdulfattah <iifawzie@gmail.com>

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you, that was incredibly fast!

**Comment by williamdes** [comment]
phpstan had found it 👻 😄

**Comment by iifawzi** [comment]
@williamdes , I've added https://github.com/iifawzi/sql-parser/commit/0cfa6a17060d58c7ea7ab56631f47a165d92f55e, can you manage to get this merged? or should I create another PR?

Added the tests to the provider, I've missed that. and renamed them to follow our namings way

**Comment by williamdes** [comment]
> @williamdes , I've added [iifawzi@0cfa6a1](https://github.com/iifawzi/sql-parser/commit/0cfa6a17060d58c7ea7ab56631f47a165d92f55e), can you manage to get this merged? or should I create another PR?
> 
> Added the tests to the provider, I've missed that. and renamed them to follow our namings way

I pushed it as 1a5b97c31ec65a2adfb31403ebfb4563edc29d7f 🚀

**Pull request merged**
