### PR TITLE
Fix #16057 Don't allow numbers with letters

### PR DESCRIPTION
**Pull request by Tithugues**
Fix https://github.com/phpmyadmin/phpmyadmin/issues/16057

### CODE REVIEW

**Comment by Tithugues** [comment]
The `parseNumber` was stopping the parsing of a number when finding another character than ".", "e" or "E". But, if you have this kind of string: `0search`, this is not a number. That's what the `parseNumber` tries to detect now.

**Comment by williamdes** [comment]
Okay, perfect then
Do you see any test case that could be added to cover the case where the parser should stop ?

**Comment by Tithugues** [comment]
I'm sure that there are… But the test system with the `parse.out` files is so unusable that I should confess I'm a bit discouraged…

**Comment by williamdes** [comment]
> I'm sure that there are… But the test system with the parse.out files is so unusable that I should confess I'm a bit discouraged…

I agree, It is impossible to read and view diffs
I hate that
I have a proposal to change the system would be using json_encode and json_decode

**Comment by williamdes** [comment]
Merged !
Thank you !

**Pull request merged**
