### PR TITLE
fix #168 - error on test SET statement

### LINKED ISSUE #168: SET statement / SET type
It seems that the parser seems to treat SET as statement even when it should not:

```console
./bin/lint-query --query 'ALTER TABLE `table_name` ADD `new_column_name` SET ('value1','value2','value3') NOT NULL AFTER `another_column`'
#1: A new statement was found, but no delimiter between it and the previous one. (near "SET" at position 47)
#2: Unrecognized alter operation. (near "," at position 65)
#3: Unrecognized alter operation. (near "" at position 0)
```

See https://github.com/phpmyadmin/phpmyadmin/issues/13636

### PR DESCRIPTION
**Pull request by BorisValgo**
Fixes: #168

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @BorisValgo 
Could you give or add test cases for that ?

**Comment by BorisValgo** [comment]
Hi,

For a test case you can try this : 
`./bin/lint-query --query 'ALTER TABLE `table_name` ADD `new_column_name` SET ('value1','value2','value3') NOT NULL AFTER another_column'`

Or without space between "SET" and "(" :
`./bin/lint-query --query 'ALTER TABLE `table_name` ADD `new_column_name` SET('value1','value2','value3') NOT NULL AFTER another_column'`

This tests might not display errors.

See also [SET statement / SET type](https://github.com/phpmyadmin/sql-parser/issues/168) or [Delimiter error](https://github.com/phpmyadmin/phpmyadmin/issues/13636)

**Comment by williamdes** [comment]
I added two test cases for this in ded1fea0494bafb2c1454264283d2e5222ce4da7

**Comment by williamdes** [comment]
I changed the format of outputs in 9f16b246ba0752b0cbf568e469cb2559cb3ace4a
And now I can see locally that your PR does fix the case [11](https://github.com/phpmyadmin/sql-parser/blob/master/tests/data/parser/parseAlter11.in) but not [12](https://github.com/phpmyadmin/sql-parser/blob/master/tests/data/parser/parseAlter12.in)

The error still exists:
https://github.com/phpmyadmin/sql-parser/blob/9f16b246ba0752b0cbf568e469cb2559cb3ace4a/tests/data/parser/parseAlter12.out#L673-L684

**Comment by williamdes** [comment]
Adding 
```php

                                || $list->tokens[$list->idx + 2]->value === 'DEFAULT'
```
Fixes it but does not make the tokens recognised

**Comment by williamdes** [comment]
Hi @BorisValgo 
I added the case for `DEFAULT` keyword
I think if the user has 3 spaces the code will break
Maybe this is not done right, I will try to search further

**Comment by williamdes** [comment]
You can see on the diff the errors are removed but more not recognized tokens are added
<details><summary>Here is the diff of a merge into master</summary>
<p>

```diff
diff --git a/src/Components/AlterOperation.php b/src/Components/AlterOperation.php
index b43a5e3f..717f465d 100644
--- a/src/Components/AlterOperation.php
+++ b/src/Components/AlterOperation.php
@@ -285,7 +285,16 @@ class AlterOperation extends Component
                         // We have reached the end of ALTER operation and suddenly found
                         // a start to new statement, but have not find a delimiter between them
 
-                        if (! ($token->value === 'SET' && $list->tokens[$list->idx - 1]->value === 'CHARACTER')) {
+                        if (
+                            ! ($token->value === 'SET' &&
+                            (
+                                $list->tokens[$list->idx - 1]->value === 'CHARACTER'
+                                || $list->tokens[$list->idx + 1]->value === '('
+                                || $list->tokens[$list->idx + 2]->value === '('
+                                || $list->tokens[$list->idx + 2]->value === 'DEFAULT'
+                            )
+                            )
+                        ) {
                             $parser->error(
                                 'A new statement was found, but no delimiter between it and the previous one.',
                                 $token
diff --git a/tests/data/parser/parseAlter11.out b/tests/data/parser/parseAlter11.out
index af11cc94..e46f1359 100644
--- a/tests/data/parser/parseAlter11.out
+++ b/tests/data/parser/parseAlter11.out
@@ -719,259 +719,31 @@
                             "function": null,
                             "subquery": null
                         },
-                        "unknown": []
-                    },
-                    {
-                        "@type": "PhpMyAdmin\\SqlParser\\Components\\AlterOperation",
-                        "DB_OPTIONS": {
-                            "CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "UPGRADE": [
-                                1,
-                                "var"
-                            ],
-                            "COLLATE": [
-                                2,
-                                "var"
-                            ],
-                            "DEFAULT COLLATE": [
-                                2,
-                                "var"
-                            ]
-                        },
-                        "TABLE_OPTIONS": {
-                            "ENGINE": [
-                                1,
-                                "var="
-                            ],
-                            "AUTO_INCREMENT": [
-                                1,
-                                "var="
-                            ],
-                            "AVG_ROW_LENGTH": [
-                                1,
-                                "var"
-                            ],
-                            "MAX_ROWS": [
-                                1,
-                                "var"
-                            ],
-                            "ROW_FORMAT": [
-                                1,
-                                "var"
-                            ],
-                            "COMMENT": [
-                                1,
-                                "var"
-                            ],
-                            "ADD": 1,
-                            "ALTER": 1,
-                            "ANALYZE": 1,
-                            "CHANGE": 1,
-                            "CHECK": 1,
-                            "COALESCE": 1,
-                            "CONVERT": 1,
-                            "DISABLE": 1,
-                            "DISCARD": 1,
-                            "DROP": 1,
-                            "ENABLE": 1,
-                            "IMPORT": 1,
-                            "MODIFY": 1,
-                            "OPTIMIZE": 1,
-                            "ORDER": 1,
-                            "PARTITION": 1,
-                            "REBUILD": 1,
-                            "REMOVE": 1,
-                            "RENAME": 1,
-                            "REORGANIZE": 1,
-                            "REPAIR": 1,
-                            "UPGRADE": 1,
-                            "COLUMN": 2,
-                            "CONSTRAINT": 2,
-                            "DEFAULT": 2,
-                            "TO": 2,
-                            "BY": 2,
-                            "FOREIGN": 2,
-                            "FULLTEXT": 2,
-                            "KEY": 2,
-                            "KEYS": 2,
-                            "PARTITIONING": 2,
-                            "PRIMARY KEY": 2,
-                            "SPATIAL": 2,
-                            "TABLESPACE": 2,
-                            "INDEX": 2
-                        },
-                        "VIEW_OPTIONS": {
-                            "AS": 1
-                        },
-                        "options": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\OptionsArray",
-                            "options": []
-                        },
-                        "field": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\Expression",
-                            "ALLOWED_KEYWORDS": {
-                                "AS": 1,
-                                "DUAL": 1,
-                                "NULL": 1,
-                                "REGEXP": 1,
-                                "CASE": 1,
-                                "DIV": 1,
-                                "AND": 1,
-                                "OR": 1,
-                                "XOR": 1,
-                                "NOT": 1,
-                                "MOD": 1
+                        "unknown": [
+                            {
+                                "@type": "@12"
                             },
-                            "database": null,
-                            "table": null,
-                            "column": "value2",
-                            "expr": "'value2'",
-                            "alias": null,
-                            "function": null,
-                            "subquery": null
-                        },
-                        "unknown": []
-                    },
-                    {
-                        "@type": "PhpMyAdmin\\SqlParser\\Components\\AlterOperation",
-                        "DB_OPTIONS": {
-                            "CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "UPGRADE": [
-                                1,
-                                "var"
-                            ],
-                            "COLLATE": [
-                                2,
-                                "var"
-                            ],
-                            "DEFAULT COLLATE": [
-                                2,
-                                "var"
-                            ]
-                        },
-                        "TABLE_OPTIONS": {
-                            "ENGINE": [
-                                1,
-                                "var="
-                            ],
-                            "AUTO_INCREMENT": [
-                                1,
-                                "var="
-                            ],
-                            "AVG_ROW_LENGTH": [
-                                1,
-                                "var"
-                            ],
-                            "MAX_ROWS": [
-                                1,
-                                "var"
-                            ],
-                            "ROW_FORMAT": [
-                                1,
-                                "var"
-                            ],
-                            "COMMENT": [
-                                1,
-                                "var"
-                            ],
-                            "ADD": 1,
-                            "ALTER": 1,
-                            "ANALYZE": 1,
-                            "CHANGE": 1,
-                            "CHECK": 1,
-                            "COALESCE": 1,
-                            "CONVERT": 1,
-                            "DISABLE": 1,
-                            "DISCARD": 1,
-                            "DROP": 1,
-                            "ENABLE": 1,
-                            "IMPORT": 1,
-                            "MODIFY": 1,
-                            "OPTIMIZE": 1,
-                            "ORDER": 1,
-                            "PARTITION": 1,
-                            "REBUILD": 1,
-                            "REMOVE": 1,
-                            "RENAME": 1,
-                            "REORGANIZE": 1,
-                            "REPAIR": 1,
-                            "UPGRADE": 1,
-                            "COLUMN": 2,
-                            "CONSTRAINT": 2,
-                            "DEFAULT": 2,
-                            "TO": 2,
-                            "BY": 2,
-                            "FOREIGN": 2,
-                            "FULLTEXT": 2,
-                            "KEY": 2,
-                            "KEYS": 2,
-                            "PARTITIONING": 2,
-                            "PRIMARY KEY": 2,
-                            "SPATIAL": 2,
-                            "TABLESPACE": 2,
-                            "INDEX": 2
-                        },
-                        "VIEW_OPTIONS": {
-                            "AS": 1
-                        },
-                        "options": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\OptionsArray",
-                            "options": []
-                        },
-                        "field": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\Expression",
-                            "ALLOWED_KEYWORDS": {
-                                "AS": 1,
-                                "DUAL": 1,
-                                "NULL": 1,
-                                "REGEXP": 1,
-                                "CASE": 1,
-                                "DIV": 1,
-                                "AND": 1,
-                                "OR": 1,
-                                "XOR": 1,
-                                "NOT": 1,
-                                "MOD": 1
+                            {
+                                "@type": "@13"
+                            },
+                            {
+                                "@type": "@14"
+                            },
+                            {
+                                "@type": "@15"
+                            },
+                            {
+                                "@type": "@16"
+                            },
+                            {
+                                "@type": "@17"
+                            },
+                            {
+                                "@type": "@18"
+                            },
+                            {
+                                "@type": "@19"
                             },
-                            "database": null,
-                            "table": null,
-                            "column": "value3",
-                            "expr": "'value3'",
-                            "alias": null,
-                            "function": null,
-                            "subquery": null
-                        },
-                        "unknown": [
                             {
                                 "@type": "@20"
                             },
@@ -1027,28 +799,6 @@
     },
     "errors": {
         "lexer": [],
-        "parser": [
-            [
-                "A new statement was found, but no delimiter between it and the previous one.",
-                {
-                    "@type": "@12"
-                },
-                0
-            ],
-            [
-                "Unrecognized alter operation.",
-                {
-                    "@type": "@18"
-                },
-                0
-            ],
-            [
-                "Unrecognized alter operation.",
-                {
-                    "@type": "@27"
-                },
-                0
-            ]
-        ]
+        "parser": []
     }
 }
\ No newline at end of file
diff --git a/tests/data/parser/parseAlter12.out b/tests/data/parser/parseAlter12.out
index bdd0480c..360ab799 100644
--- a/tests/data/parser/parseAlter12.out
+++ b/tests/data/parser/parseAlter12.out
@@ -638,7 +638,23 @@
                             "function": null,
                             "subquery": null
                         },
-                        "unknown": []
+                        "unknown": [
+                            {
+                                "@type": "@12"
+                            },
+                            {
+                                "@type": "@13"
+                            },
+                            {
+                                "@type": "@14"
+                            },
+                            {
+                                "@type": "@15"
+                            },
+                            {
+                                "@type": "@16"
+                            }
+                        ]
                     }
                 ],
                 "OPTIONS": {
@@ -672,14 +688,6 @@
     },
     "errors": {
         "lexer": [],
-        "parser": [
-            [
-                "A new statement was found, but no delimiter between it and the previous one.",
-                {
-                    "@type": "@12"
-                },
-                0
-            ]
-        ]
+        "parser": []
     }
 }
\ No newline at end of file
diff --git a/tests/data/parser/parseAlter13.out b/tests/data/parser/parseAlter13.out
index 9677381a..eb8beca8 100644
--- a/tests/data/parser/parseAlter13.out
+++ b/tests/data/parser/parseAlter13.out
@@ -665,259 +665,31 @@
                             "function": null,
                             "subquery": null
                         },
-                        "unknown": []
-                    },
-                    {
-                        "@type": "PhpMyAdmin\\SqlParser\\Components\\AlterOperation",
-                        "DB_OPTIONS": {
-                            "CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "UPGRADE": [
-                                1,
-                                "var"
-                            ],
-                            "COLLATE": [
-                                2,
-                                "var"
-                            ],
-                            "DEFAULT COLLATE": [
-                                2,
-                                "var"
-                            ]
-                        },
-                        "TABLE_OPTIONS": {
-                            "ENGINE": [
-                                1,
-                                "var="
-                            ],
-                            "AUTO_INCREMENT": [
-                                1,
-                                "var="
-                            ],
-                            "AVG_ROW_LENGTH": [
-                                1,
-                                "var"
-                            ],
-                            "MAX_ROWS": [
-                                1,
-                                "var"
-                            ],
-                            "ROW_FORMAT": [
-                                1,
-                                "var"
-                            ],
-                            "COMMENT": [
-                                1,
-                                "var"
-                            ],
-                            "ADD": 1,
-                            "ALTER": 1,
-                            "ANALYZE": 1,
-                            "CHANGE": 1,
-                            "CHECK": 1,
-                            "COALESCE": 1,
-                            "CONVERT": 1,
-                            "DISABLE": 1,
-                            "DISCARD": 1,
-                            "DROP": 1,
-                            "ENABLE": 1,
-                            "IMPORT": 1,
-                            "MODIFY": 1,
-                            "OPTIMIZE": 1,
-                            "ORDER": 1,
-                            "PARTITION": 1,
-                            "REBUILD": 1,
-                            "REMOVE": 1,
-                            "RENAME": 1,
-                            "REORGANIZE": 1,
-                            "REPAIR": 1,
-                            "UPGRADE": 1,
-                            "COLUMN": 2,
-                            "CONSTRAINT": 2,
-                            "DEFAULT": 2,
-                            "TO": 2,
-                            "BY": 2,
-                            "FOREIGN": 2,
-                            "FULLTEXT": 2,
-                            "KEY": 2,
-                            "KEYS": 2,
-                            "PARTITIONING": 2,
-                            "PRIMARY KEY": 2,
-                            "SPATIAL": 2,
-                            "TABLESPACE": 2,
-                            "INDEX": 2
-                        },
-                        "VIEW_OPTIONS": {
-                            "AS": 1
-                        },
-                        "options": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\OptionsArray",
-                            "options": []
-                        },
-                        "field": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\Expression",
-                            "ALLOWED_KEYWORDS": {
-                                "AS": 1,
-                                "DUAL": 1,
-                                "NULL": 1,
-                                "REGEXP": 1,
-                                "CASE": 1,
-                                "DIV": 1,
-                                "AND": 1,
-                                "OR": 1,
-                                "XOR": 1,
-                                "NOT": 1,
-                                "MOD": 1
+                        "unknown": [
+                            {
+                                "@type": "@12"
                             },
-                            "database": null,
-                            "table": null,
-                            "column": "value2",
-                            "expr": "'value2'",
-                            "alias": null,
-                            "function": null,
-                            "subquery": null
-                        },
-                        "unknown": []
-                    },
-                    {
-                        "@type": "PhpMyAdmin\\SqlParser\\Components\\AlterOperation",
-                        "DB_OPTIONS": {
-                            "CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARACTER SET": [
-                                1,
-                                "var"
-                            ],
-                            "DEFAULT CHARSET": [
-                                1,
-                                "var"
-                            ],
-                            "UPGRADE": [
-                                1,
-                                "var"
-                            ],
-                            "COLLATE": [
-                                2,
-                                "var"
-                            ],
-                            "DEFAULT COLLATE": [
-                                2,
-                                "var"
-                            ]
-                        },
-                        "TABLE_OPTIONS": {
-                            "ENGINE": [
-                                1,
-                                "var="
-                            ],
-                            "AUTO_INCREMENT": [
-                                1,
-                                "var="
-                            ],
-                            "AVG_ROW_LENGTH": [
-                                1,
-                                "var"
-                            ],
-                            "MAX_ROWS": [
-                                1,
-                                "var"
-                            ],
-                            "ROW_FORMAT": [
-                                1,
-                                "var"
-                            ],
-                            "COMMENT": [
-                                1,
-                                "var"
-                            ],
-                            "ADD": 1,
-                            "ALTER": 1,
-                            "ANALYZE": 1,
-                            "CHANGE": 1,
-                            "CHECK": 1,
-                            "COALESCE": 1,
-                            "CONVERT": 1,
-                            "DISABLE": 1,
-                            "DISCARD": 1,
-                            "DROP": 1,
-                            "ENABLE": 1,
-                            "IMPORT": 1,
-                            "MODIFY": 1,
-                            "OPTIMIZE": 1,
-                            "ORDER": 1,
-                            "PARTITION": 1,
-                            "REBUILD": 1,
-                            "REMOVE": 1,
-                            "RENAME": 1,
-                            "REORGANIZE": 1,
-                            "REPAIR": 1,
-                            "UPGRADE": 1,
-                            "COLUMN": 2,
-                            "CONSTRAINT": 2,
-                            "DEFAULT": 2,
-                            "TO": 2,
-                            "BY": 2,
-                            "FOREIGN": 2,
-                            "FULLTEXT": 2,
-                            "KEY": 2,
-                            "KEYS": 2,
-                            "PARTITIONING": 2,
-                            "PRIMARY KEY": 2,
-                            "SPATIAL": 2,
-                            "TABLESPACE": 2,
-                            "INDEX": 2
-                        },
-                        "VIEW_OPTIONS": {
-                            "AS": 1
-                        },
-                        "options": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\OptionsArray",
-                            "options": []
-                        },
-                        "field": {
-                            "@type": "PhpMyAdmin\\SqlParser\\Components\\Expression",
-                            "ALLOWED_KEYWORDS": {
-                                "AS": 1,
-                                "DUAL": 1,
-                                "NULL": 1,
-                                "REGEXP": 1,
-                                "CASE": 1,
-                                "DIV": 1,
-                                "AND": 1,
-                                "OR": 1,
-                                "XOR": 1,
-                                "NOT": 1,
-                                "MOD": 1
+                            {
+                                "@type": "@13"
+                            },
+                            {
+                                "@type": "@14"
+                            },
+                            {
+                                "@type": "@15"
+                            },
+                            {
+                                "@type": "@16"
+                            },
+                            {
+                                "@type": "@17"
+                            },
+                            {
+                                "@type": "@18"
+                            },
+                            {
+                                "@type": "@19"
                             },
-                            "database": null,
-                            "table": null,
-                            "column": "value3",
-                            "expr": "'value3'",
-                            "alias": null,
-                            "function": null,
-                            "subquery": null
-                        },
-                        "unknown": [
                             {
                                 "@type": "@20"
                             }
@@ -955,28 +727,6 @@
     },
     "errors": {
         "lexer": [],
-        "parser": [
-            [
-                "A new statement was found, but no delimiter between it and the previous one.",
-                {
-                    "@type": "@12"
-                },
-                0
-            ],
-            [
-                "Unrecognized alter operation.",
-                {
-                    "@type": "@18"
-                },
-                0
-            ],
-            [
-                "Unrecognized alter operation.",
-                {
-                    "@type": "@21"
-                },
-                0
-            ]
-        ]
+        "parser": []
     }
 }
\ No newline at end of file
diff --git a/tests/data/parser/parseAlterErr4.out b/tests/data/parser/parseAlterErr4.out
index c8ce4a94..e6cb5aa2 100644
--- a/tests/data/parser/parseAlterErr4.out
+++ b/tests/data/parser/parseAlterErr4.out
@@ -638,7 +638,26 @@
                             "function": null,
                             "subquery": null
                         },
-                        "unknown": []
+                        "unknown": [
+                            {
+                                "@type": "@12"
+                            },
+                            {
+                                "@type": "@13"
+                            },
+                            {
+                                "@type": "@14"
+                            },
+                            {
+                                "@type": "@15"
+                            },
+                            {
+                                "@type": "@16"
+                            },
+                            {
+                                "@type": "@17"
+                            }
+                        ]
                     }
                 ],
                 "OPTIONS": {
@@ -679,14 +698,6 @@
                 0
             ]
         ],
-        "parser": [
-            [
-                "A new statement was found, but no delimiter between it and the previous one.",
-                {
-                    "@type": "@12"
-                },
-                0
-            ]
-        ]
+        "parser": []
     }
 }
\ No newline at end of file
```

</p>
</details>

**Comment by williamdes** [comment]
Thank you for your work @BorisValgo 
It is now fixed by #344

**Pull request closed without merging**
