### PR TITLE
Fix #226 - Ignore end of comment string at the end of queries with MySQL-specific commands

### LINKED ISSUE #226: Parser leaves comment string at the end of the query in mysql-specific comment
When parsing SQL with MySQL specific comments `/*! ... */` (https://dev.mysql.com/doc/refman/5.7/en/comments.html), parser leaves ending comment in parsed query: `*/`.

I would expect either ignore all MySQL specific comments or remove the remaining comment part from 
the end of the query.

Here is full PHP unit test for this case:

```php
public function testMysqldump()
{
    $sql = <<<SQL
-- MySQL dump 10.13  Distrib 5.7.24, for Linux (x86_64)ldump e-nocleg-2-dev 01-te
--
-- Host: localhost    Database: x
-- ------------------------------------------------------
-- Server version	5.7.24

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
SQL;

    $expectedSql = [
        'SET  @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT',
        'SET  @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS',
        'SET  @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION',
        'SET NAMES utf8',
        'SET  @OLD_TIME_ZONE = @@TIME_ZONE',
        "SET  TIME_ZONE = '+00:00'",
        'SET  @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0',
        'SET  @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0',
        "SET  @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO'",
        'SET  @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0',
    ];

    $parser = new Parser($sql, true);
    $parser->parse();

    $sql = [];
    foreach($parser->statements as $stmt) {
        $sql[] = $stmt->__toString();
    }
    
    $this->assertEquals($expectedSql, $sql);
}
```

Current result is:
```
Array
(
    [0] => SET  @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT */
    [1] => SET  @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS */
    [2] => SET  @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION */
    [3] => SET NAMES utf8
    [4] => SET  @OLD_TIME_ZONE = @@TIME_ZONE */
    [5] => SET  TIME_ZONE = '+00:00'
    [6] => SET  @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0 */
    [7] => SET  @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */
    [8] => SET  @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO'
    [9] => SET  @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0 */
)
```

Expected result:
```
Array
(
    [0] => SET  @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT
    [1] => SET  @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS
    [2] => SET  @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION
    [3] => SET NAMES utf8
    [4] => SET  @OLD_TIME_ZONE = @@TIME_ZONE
    [5] => SET  TIME_ZONE = '+00:00'
    [6] => SET  @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0
    [7] => SET  @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0
    [8] => SET  @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO'
    [9] => SET  @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0
)
```

### PR DESCRIPTION
**Pull request by niconoe-**
This is an attempt to fix #226 .

If it misses some use-cases to test, please tell me.

### CODE REVIEW

**Review by williamdes — COMMENTED** [review]
Thank you for working on the sql-parser 🚀
this fix only ignores the end, but without it what would the unit tests look like? 
The queries where broken?

**Comment by niconoe-** [comment]
> Thank you for working on the sql-parser 🚀
> this fix only ignores the end, but without it what would the unit tests look like?
> The queries where broken?

Kind of… if you look at the unit test defined in #226 , without the fix, the `assertEquals` fails because the content of the expression ends with the ˋ*/` token while it shouldn’t.
I don’t know how this could be interpreted but I guess if this is reused in the builder, it will create an invalid query.

**Comment by williamdes** [comment]
> Kind of… if you look at the unit test defined in https://github.com/phpmyadmin/sql-parser/issues/226 , without the fix, the assertEquals fails because the content of the expression ends with the ˋ*/` token while it shouldn’t.
I don’t know how this could be interpreted but I guess if this is reused in the builder, it will create an invalid query.

Oh okay, could you add a regression test for this ?

**Review by williamdes — APPROVED** [review]
Or maybe the current tests would fail without you fix ?

**Comment by niconoe-** [comment]
> Or maybe the current tests would fail without you fix ?

That's is. Considering the unit test `testMysqlCommands` I added, it would fail if my fix isn't provided. 

Without my fix, it behaved exactly like the issue's OP described, while with my fix, it's now OK.

**Comment by williamdes** [comment]
> > Or maybe the current tests would fail without you fix ?
> 
> That's is. Considering the unit test `testMysqlCommands` I added, it would fail if my fix isn't provided.
> 
> Without my fix, it behaved exactly like the issue's OP described, while with my fix, it's now OK.

Awesome, ready for a merge

**Comment by williamdes** [comment]
Thank you, I rebased your work after adding more test cases in: 049ed2d8048d6e5f862b18bedd7504b2e685251e

**Pull request merged**
