### PR TITLE
Use PHPUnit attributes over annotations

### PR DESCRIPTION
**Pull request by BackEndTea**
Since this project is PHPUnit 10, we might as well use the new attributes instead of the annotations

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
🎉

**Comment by BackEndTea** [comment]
It seems psalm can't detect the dataproviders as being used with the attributes yet

**Comment by williamdes** [comment]
> It seems psalm can't detect the dataproviders as being used with the attributes yet

Let's say not a big deal, phpstan can do it
Maybe @MauricioFauth knows how to make psalm happy ?

Else, run `composer run update:baselines`

**Comment by MauricioFauth** [comment]
> > It seems psalm can't detect the dataproviders as being used with the attributes yet
> 
> Let's say not a big deal, phpstan can do it
> Maybe @MauricioFauth knows how to make psalm happy ?
> 
> Else, run `composer run update:baselines`

The PHPUnit plugin for Psalm doesn't understand it yet.

**Comment by williamdes** [comment]
Thank you @BackEndTea !

**Comment by BackEndTea** [comment]
Thanks @williamdes

**Pull request merged**
