### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by voku**
Do not copy the test directory into the project, if we install it via composer.

### CODE REVIEW

**Comment by williamdes** [comment]
I can not approve this because Debian uses the `tests/` folder to run autopkg tests: https://salsa.debian.org/phpmyadmin-team/sql-parser/-/blob/debian/latest/debian/tests/phpunit
Output: https://salsa.debian.org/phpmyadmin-team/sql-parser/-/jobs/2353133

**Comment by williamdes** [comment]
> @williamdes Understand. Do you think we could use the "exclude"-setting in the composer.json here? thinking

Does it really work ?
I accept to add this, can you edit your PR ?

**Comment by Yurunsoft** [comment]
OK.
Also I would like to ask when you can release a new version, it's been almost a year since the last release.
I've encountered a bug and I'm currently using the `dev-master` version.

**Comment by williamdes** [comment]
This was released right now 🎉

**Pull request closed without merging**
