### PR TITLE
Incorrect order of operations to parse table/db called ``

### PR DESCRIPTION
**Pull request by kamil-tekiela**
A very minor error when the table name is ` `` `

### CODE REVIEW

**Comment by williamdes** [comment]
I think you you also add a new test for this, check out the recent PRs for examples
I can also do it if you don't have time

**Comment by kamil-tekiela** [comment]
@williamdes If you have time to do it I would be obliged. I don't have much familiarity with the parser yet.

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
> @williamdes If you have time to do it I would be obliged. I don't have much familiarity with the parser yet.

I added a test in 19ce4bdda01a4aafa46a40a2b103fecdc6862f6e
And updated the data (after the fix) in the merge commit: f022373ccc22c417c50f3349046be5df8d98a41c

**Review by williamdes — COMMENTED** [review]
💯

**Pull request merged**
