### PR TITLE
EXISTS also is a function-ish, not only keyword

### PR DESCRIPTION
**Pull request by m0003r**
It is not documented, but queries like `SELECT EXISTS(SELECT ....)` works perfectly in supported databases.

***UPD***: work in progress
***UPD2***: apparently it works correct. But I have a question:
how can I extract subselect expression from it?

### CODE REVIEW

**Comment by williamdes** [comment]
@m0003r Did you edit the files by hand ?
`./tools/run_generators.sh` creates them

@devenbansod could you please review this one and give some advice ?

**Comment by m0003r** [comment]
@williamdes I used scripts only for generating test `.out` (and of course verified it manually), because `run_generators.sh`  is <a href="https://github.com/phpmyadmin/sql-parser/blob/master/CONTRIBUTING.md#testsuite">mentioned only for tests</a>.

I have updated pull request and added a clarification to Context/* files, I hope it's ok

**Comment by williamdes** [comment]
Thank you @m0003r !

**Comment by williamdes** [comment]
If you want to edit the contributing file I will be happy to merge your suggestion ;)

Also could you reset your PR onto QA branch ?
Do you want me to do it ?

**Comment by m0003r** [comment]
Rebased work to QA branch and force-pushed
Hope I've done it right

**Pull request merged**
