### PR TITLE
Fix #45 FULLTEXT unrecognized data type

### LINKED ISSUE #45: FULLTEXT unrecognized data type
Using this SQL from the MySQL manual:

`
CREATE TABLE opening_lines (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
opening_line TEXT(500),
author VARCHAR(200),
title VARCHAR(200),
FULLTEXT idx (opening_line)
) ENGINE=InnoDB;`

I get a linter warning of "Unrecognized data type. (near idx)"

### PR DESCRIPTION
**Pull request by madhuracj**

### CODE REVIEW

**Comment by nijel** [comment]
You've just changed the generated files without changing their source, I guess it was not intended...

**Comment by nijel** [comment]
Also you change lead to duplicate keys in the array...

**Comment by madhuracj** [comment]
In fact I did not know that it was a generate file. Now I know that :)

**Comment by nijel** [comment]
It's written in top of the file ;-)

**Pull request closed without merging**
