### PR TITLE
Fix #445 - re-design part of `DESCRIBE`

### LINKED ISSUE #445: DESCRIBE should allow schema.table
```sql
DESC phpmyadmin.pma__users;
```
Results in an error:
> Unexpected beginning of statement (near pma__users)

Without  schema it works correctly:
```sql
DESC pma__users;
```

### PR DESCRIPTION
**Pull request by williamdes**
Fixes: #445 - re-design part of `DESCRIBE`

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @iifawzi 
I did some re-design on top of #389, would you mind having a look to my changes ?

**Comment by iifawzi** [comment]
Hi, sorry for the late replies, I've been away for a while, will take a look asap

**Comment by williamdes** [comment]
@niconoe- this PR should be the last thing to be merged for rc1
What do you think about it ?

**Review by niconoe- — APPROVED** [review]

**Comment by niconoe-** [comment]
@williamdes Seems nice to me! 👍

**Pull request merged**
