### PR TITLE
Move to GitHub actions

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by williamdes** [comment]
Thanks for adding 8.0 to the build matrix
We already support 8.0: https://github.com/phpmyadmin/sql-parser/blob/3ad940e9d481cd6cd98595931c2f54e243d93a45/composer.json#L19

**Comment by staabm** [comment]
Ohh I thought I need to fix https://github.com/phpmyadmin/sql-parser/issues/315 ?

**Comment by williamdes** [comment]
> Ohh I thought I need to fix #315 ?

Oh, sure 
I had forgot about that, well I would say we support php 8 but there is a bug somewhere for php 8.0

You can continue then, thank you ;)

**Comment by staabm** [comment]
Hm #315 seems no longer be reproducible. Maybe it was a bug in a RC release or in one of the dependencies (in phpunit itself?).

the error does not show up in the travis build, so this seems to be ready to land

**Comment by williamdes** [comment]
I edited this PR to move to GHA
And when I will merge it I will add php 8.0 for master branch

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
I added your fix in 0fb1da661c3c1cf0686f2c0f0fd5167aa77bb8e7

**Comment by staabm** [comment]
Cool thx. 

Any eta for a next release, so we can build bew releases on top of the added php8 support?

**Comment by williamdes** [comment]
> Cool thx.
> 
> Any eta for a next release, so we can build bew releases on top of the added php8 support?

cc @ibennetch 
For me the next version is ready to be released, on QA also.

**Pull request merged**
